export const lugaresUbicacion = [
  {
    id: "1",
    lat: -34.9011,
    lng: -56.1645,
    titulo: "Montevideo",
    estado: "Operativa",
  },
  { id: "2", lat: -34.878, lng: -56.0755, titulo: "Pocitos", estado: "Alerta" },
  {
    id: "3",
    lat: -34.309466,
    lng: -55.960309,
    titulo: "Casa Thiago",
    estado: "Fuera de servicio",
  },
  {
    id: "4",
    lat: -30.948706,
    lng: -57.520326,
    titulo: "Termas Arapey",
    estado: "Mantenimiento",
  },
];

export const detallesLugares = [
  {
    id: "1",
    nombreEstacion: "Montevideo",
    tipoReceptor: "GPS",
    tipoAntena: "De metal",
    alturaAntena: "10 metros",
    titulo: "Montevideo",
    estado: "Operativa",
    latencia: "18 ms",
    satelites: 24,
    disponibilidad: "99,8 %",
    estadoTexto: "Estable",
  },
  {
    id: "2",
    nombreEstacion: "Pocitos",
    tipoReceptor: "GPS",
    tipoAntena: "De metal",
    alturaAntena: "10 metros",
    titulo: "Pocitos",
    estado: "Alerta",
    latencia: "45 ms",
    satelites: 14,
    disponibilidad: "92,1 %",
    estadoTexto: "Inestable",
  },
  {
    id: "3",
    nombreEstacion: "Casa Thiago",
    tipoReceptor: "GPS",
    tipoAntena: "De metal",
    alturaAntena: "10 metros",
    titulo: "Casa Thiago",
    estado: "Fuera de servicio",
    latencia: "-- ms",
    satelites: 0,
    disponibilidad: "0 %",
    estadoTexto: "Sin señal",
  },
  {
    id: "4",
    nombreEstacion: "Termas Arapey",
    tipoReceptor: "GPS",
    tipoAntena: "De metal",
    alturaAntena: "10 metros",
    titulo: "Termas Arapey",
    estado: "Mantenimiento",
    latencia: "-- ms",
    satelites: 3,
    disponibilidad: "40 %",
    estadoTexto: "En mantenimiento",
  },
];

export const coloresEstado = {
  Operativa: "#00CC00",
  Alerta: "#FFCC00",
  "Fuera de servicio": "#CC0000",
  Mantenimiento: "#808080",
};
